arthur/arthur/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('enroll/', include('enroll.urls')),
    path('admin/', admin.site.urls),
]

arthur/enroll/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from .views.stats_views import TenantMemberListView, TenantListView

from . import views

app_name = 'edr'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('enroll', views.enroll, name='enroll'),
    path('config', views.config, name='config'),
    path('logger', views.logger, name='logger'),
    path('distributed_read', views.distributed_read, name='distributed_read'),
    path('distributed_write', views.distributed_write, name='distributed_write'),
    path('distributed_query', views.distributed_query, name='distributed_query'),
    path('distributed_results', views.distributed_results, name='distributed_results'),
    path('alert', views.alert, name='alert'),
    path('tenantList', TenantListView.as_view(), name='tenantList'),
    path('members', TenantMemberListView.as_view(), name='members'),
    path('addTenant', views.addTenant, name='addTenant'),
    path('addTenantMember', views.addTenantMember, name='addTenantMember'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('registerUser', views.RegisterView.as_view(), name='register'),
    path('hello', views.HelloView.as_view(), name='hello'),
    path('home', views.HelloView.as_view(), name='home'),
    path('token', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/register', views.RegisterNodeView.as_view(), name='api_register'),
    path('api/node_list', views.NodeList.as_view(), name='api_node_list'),
]

arthur/enroll/views/admin_views.py
# Django imports
from django.http import HttpResponseBadRequest, HttpResponseNotFound
from django.shortcuts import render
from cassandra.cqlengine.management import create_keyspace_simple, sync_table

# App imports
from ..models import EnrolledNode, Tenant, TenantMember, alerts, dist_query_result, live_query
from ..forms.tenantForm import TenantForm
from ..forms.tenantMemberForm import TenantMemberForm
from ..settings import *
from ..utils import hostname_from_request

#Miscellaneous imports
from passlib.hash import pbkdf2_sha256
import os, string, random

# Endpoint for registering new nodes
def addTenantMember(request):
    if hostname_from_request(request) != 'admin':
        return HttpResponseNotFound('Page not found')
    if request.method == 'GET':
        form = TenantMemberForm()
        #form.helper.build_default_layout()
        #form.tenant.choices = [(tenant.tenant_name, tenant.tenant_name) for tenant in Tenant.objects().all()]
        return render(request, 'enroll/administer/add_tenant_member.html', {'form': form})
    elif request.method == 'POST':
        form = TenantMemberForm(request.POST)
        if form.is_valid():
            member_name = form.cleaned_data['member_name']
            member_email = form.cleaned_data['member_email']
            member_password = form.cleaned_data['member_password']
            tenant_name = form.cleaned_data['tenant']
        tenant = Tenant.objects(tenant_name=tenant_name)
        if not tenant:
            raise HttpResponseBadRequest("Invalid details!!")
        else:
            tenant = tenant[0]
        # tenantMember = TenantMember.objects(member_username=member_username)
        # if tenantMember:
        #     raise HttpResponseBadRequest("Invalid details!!")
        member_password_hash = pbkdf2_sha256.hash(member_password)
        #TenantMember.__keyspace__= tenant.tenant_schema
        if TenantMember.objects.filter(email=member_email):
            return HttpResponseBadRequest("Invalid details!!")
        tenantMember = TenantMember(username=member_name, email=member_email, password=member_password_hash, tenant_id=tenant.tenant_id)
        tenantMember.save()
        context = {"message": 'Tenant member {} added successfully!!'.format(member_email)}
        return render(request, 'enroll/miscellaneous/success.html', context)

def addTenant(request):
    if hostname_from_request(request) != 'admin':
        return HttpResponseNotFound('Page not found')
    if request.method == 'GET':
        form = TenantForm()
        return render(request, 'enroll/administer/add_tenant.html', {'form': form})
    elif request.method == 'POST':
        form = TenantForm(request.POST)
        if form.is_valid():
            tenant_name = form.cleaned_data['tenant_name']
        domain_space = string.ascii_lowercase + string.digits
        tenant_domain = ''.join(random.choice(domain_space) for i in range(10))
        tenant = Tenant.objects(tenant_name=tenant_name)
        if tenant:
            raise HttpResponseBadRequest("Invalid details!!")
        tenant = Tenant(tenant_name=tenant_name, tenant_domain=tenant_domain, tenant_schema = tenant_name)
        tenant.save()
        create_keyspace_simple(tenant_name,replication_factor=1)
        #sync_type(ks_name=tenant_domain, type_model=Tenant)
        sync_table(keyspaces=[tenant_name], model=TenantMember)
        sync_table(keyspaces=[tenant_name], model=EnrolledNode)
        sync_table(keyspaces=[tenant_name], model=alerts)
        sync_table(keyspaces=[tenant_name], model=live_query)
        sync_table(keyspaces=[tenant_name], model=dist_query_result)
        #TenantMemberForm()
        os.system("./enroll/certs/generate_new_cert.sh " + tenant_domain)
        os.system("echo '127.0.0.1   " + tenant_domain + ".edr.api' >> /etc/hosts")
        context = {"message": 'Tenant {} added successfully!!'.format(tenant_name)}
        return render(request, 'enroll/miscellaneous/success.html', context)

arthur/enroll/views/api_views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated  # <-- Here
from django.http import HttpResponse, HttpResponseBadRequest, FileResponse, JsonResponse
from django.core import serializers

# App imports
from ..models import Tenant
from ..forms.enrollForm import EnrollForm
from ..models import EnrolledNode
from ..utils import hostname_from_request
from ..enroll import Enrollment

import json, zipfile

class HelloView(APIView):
    permission_classes = (IsAuthenticated,)             # <-- And here

    def get(self, request):
        content = {'message': 'Hello, World!'}
        return Response(content)

class RegisterNodeView(APIView):
    permission_classes = (IsAuthenticated,) 

    def post(self,request):
        tenant = Tenant.objects(tenant_domain=hostname_from_request(request))
        if tenant:
            tenant = tenant[0]
        else:
            return HttpResponseBadRequest("Invalid details!!")
        data = request.body.decode('utf-8')
        json_data = json.loads(data)
        tenant_id = tenant.tenant_id
        node_system_id = json_data.get('system_id')
        os = json_data.get('os')
        arch = json_data.get('arch')
        #Tenant.__keyspace__ = "db"
        try:
            host_enroll = Enrollment(tenant_id=tenant_id, node_system_id=node_system_id)
        except Exception:
            return HttpResponseBadRequest("Invalid details!!")
        secret = host_enroll.generate_node(node_arch=arch, node_os=os)
        # with open(tenant.tenant_name+'_'+node_system_id+'.secret', 'x') as f:
        #     f.write(secret)
        osquery_flag_string = """--tls_hostname="""+tenant.tenant_domain+""".edr.api:8000
                --tls_server_certs=./ca.pem
                --enroll_secret_path=./"""+tenant.tenant_name+'_'+node_system_id+""".secret
                --enroll_tls_endpoint=/enroll/enroll
                --host_identifier=uuid
                --distributed_tls_read_endpoint=/enroll/distributed_read
                --distributed_tls_write_endpoint=/enroll/distributed_write
                --disable_distributed=false
                --distributed_interval=5
                --distributed_plugin=tls

                --config_plugin=tls
                #--config_refresh=5
                --config_tls_endpoint=/enroll/config
                --logger_plugin=tls
                --logger_tls_endpoint=/enroll/logger"""
        cert_file = open('./ca.pem', 'r')
        cert_string = cert_file.read()
        return JsonResponse({'secret': secret, 'flag': osquery_flag_string, 'cert': cert_string})
        #return HttpResponse('Generated Secret: ' + secret)

class LiveQueryView(APIView):
    pass

class LogsView(APIView):
    pass

class NodeList(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        tenant = Tenant.objects(tenant_domain=hostname_from_request(request))
        if tenant:
            tenant = tenant[0]
        else:
            return HttpResponseBadRequest("Invalid details!!")
        tenant_id = tenant.tenant_id
        node_list = {}
        nodes = EnrolledNode.objects(tenant_id=tenant_id)
        if nodes:
            for node in nodes:
                node_list[node.node_id.urn.split(':')[-1]] = node.node_info
        else:
            node_list['msg'] = 'No registered nodes!!'
        return JsonResponse(node_list)


class RegisterMultipleNodes(APIView):
    permission_classes = (IsAuthenticated,)             # <-- And here

    def post(self, request):
        data = request.body.decode('utf-8')
        json_data = json.loads(data)
        print(json_data)
        return_json = '{'
        for deserialized_object in serializers.deserialize("jsonl", data):
            host_enroll = Enrollment(tenant_id=deserialized_object.tenant_id, node_system_id=deserialized_object.node_system_id)
            if host_enroll:
                secret = host_enroll.generate_node(node_arch=deserialized_object.arch, node_os=deserialized_object.os)
                if secret:
                    return_json += "{'node_system_id': '" + deserialized_object.node_system_id + "', 'message': 'Registration successful!!', 'secret': '" + secret + "'},"
                else:
                    return_json += "{'node_system_id': " + deserialized_object.node_system_id + ", 'message': 'Registration failed!!'},"    
            else:
                return_json += "{'node_system_id': " + deserialized_object.node_system_id + ", 'message': 'Registration failed!!'},"
        return_json += "}"
        return JsonResponse(return_json)

arthur/enroll/views/enroll_views.py
# Django imports
from django.http import HttpResponse, HttpResponseBadRequest, FileResponse, JsonResponse
from django.shortcuts import render
from django import forms
from django.views.decorators.csrf import csrf_exempt

from .kafka_views import kfk

# App imports
from ..models import Logs, Tenant, alerts
from ..forms.enrollForm import EnrollForm
from ..enroll import Enrollment
from ..osqueryResponses import *
from ..settings import *
from ..alerts import *
from ..utils import hostname_from_request

#Miscellaneous imports
import zipfile, json
from copy import deepcopy

def index(request):
    return render(request, 'enroll/index.html')

# Endpoint for registering new nodes
def register(request):
    if request.method == 'GET':
        tenant = Tenant.objects(tenant_domain=hostname_from_request(request))
        if tenant:
            tenant = tenant[0]
        else:
            return HttpResponseBadRequest("Invalid details!!")
        form = EnrollForm(tenant)
        return render(request, 'enroll/enroll.html', {'form': form})
    elif request.method == 'POST':
        tenant = Tenant.objects(tenant_domain=hostname_from_request(request))
        if tenant:
            tenant = tenant[0]
        else:
            return HttpResponseBadRequest("Invalid details!!")
        form = EnrollForm(tenant, request.POST)
        if form.is_valid():
            tenant_id = form.cleaned_data['tenant_id']
            node_system_id = form.cleaned_data['system_id']
            os = form.cleaned_data['os']
            arch = form.cleaned_data['arch']
        #Tenant.__keyspace__ = "db"
        tenant = Tenant.objects(tenant_id=tenant_id)
        if tenant:
            tenant = tenant[0]
        else:
            return HttpResponseBadRequest("Invalid details!!")
        try:
            host_enroll = Enrollment(tenant_id=tenant_id, node_system_id=node_system_id)
        except Exception:
            return HttpResponseBadRequest("Invalid details!!")
        secret = host_enroll.generate_node(node_arch=arch, node_os=os)
        with open(tenant.tenant_name+'_'+node_system_id+'.secret', 'x') as f:
            f.write(secret)
        osquery_flag_string = """--tls_hostname="""+tenant.tenant_domain+""".edr.api:8000
                --tls_server_certs=./ca.pem
                --enroll_secret_path=./"""+tenant.tenant_name+'_'+node_system_id+""".secret
                --enroll_tls_endpoint=/enroll/enroll
                --host_identifier=uuid
                --distributed_tls_read_endpoint=/enroll/distributed_read
                --distributed_tls_write_endpoint=/enroll/distributed_write
                --disable_distributed=false
                --distributed_interval=5
                --distributed_plugin=tls

                --config_plugin=tls
                #--config_refresh=5
                --config_tls_endpoint=/enroll/config
                --logger_plugin=tls
                --logger_tls_endpoint=/enroll/logger"""
        with open(tenant.tenant_name+'_'+node_system_id+'.flags', 'x') as f:
            f.write(osquery_flag_string)
        zf = zipfile.ZipFile(tenant.tenant_name+'_'+node_system_id+".zip", 'x')
        zf.write(tenant.tenant_name+'_'+node_system_id+'.secret')
        zf.write(tenant.tenant_name+'_'+node_system_id+'.flags')
        zf.write('ca.pem')
        zf.close()
        zip_file = open(tenant.tenant_name+'_'+node_system_id+".zip", 'rb')
        return FileResponse(zip_file)
        #return HttpResponse('Generated Secret: ' + secret)

@csrf_exempt
def enroll(request):
    if request.method == 'GET':
        return JsonResponse(FAILED_ENROLL_RESPONSE)
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        json_data = json.loads(data)
        print(json_data)
        enroll_secret = json_data.get('enroll_secret')
        host = Enrollment(tenant_id=None, node_system_id=None)
        try:
            node = host.validate_enroll_secret(enroll_secret)
            if not enroll_secret or not node:
                return JsonResponse(FAILED_ENROLL_RESPONSE)
        except Exception:
            return JsonResponse(FAILED_ENROLL_RESPONSE)
        
        node_key = host.update_node_info(data)
        response = ENROLL_RESPONSE
        response['node_key'] = node_key
        print(node_key.int)
        print(node_key.node)

        return JsonResponse(response)


@csrf_exempt
def config(request):
    if request.method == 'POST':
        data = request.body.decode('utf-8')
        json_data = json.loads(data)
        print(json_data)
        address = request.META.get('REMOTE_ADDR')
        node_id = json_data.get('node_key')

        host = Enrollment(tenant_id=None, node_system_id=None)
        node = host.validate_node(node_id)
        if not node:
            return JsonResponse(FAILED_ENROLL_RESPONSE)

        return JsonResponse(TEST_SCHED_QUERY)


@csrf_exempt
def logger(request):

    data = request.body.decode('utf-8')
    json_data = json.loads(data)
    print(json_data)
    address = request.META.get('REMOTE_ADDR')
    logs = json_data.get('data')
    log_type = json_data.get('log_type')
    node_id = json_data.get('node_key')

    host = Enrollment(tenant_id=None, node_system_id=None)
    node = host.validate_node(node_id)
    if not node:
        return JsonResponse(FAILED_ENROLL_RESPONSE)

    if logs and log_type == 'result':
        #kfk(results)
        for log in logs:
            new_log = Logs(node_id=node_id, log_type=log['name'], log_data=json.dumps(log['columns']).strip(), log_ts=log['unixTime'], log_action=log['action'])
            new_log.save()
    return JsonResponse({'msg': 'Saved the logs!!'})
    #return JsonResponse(EMPTY_RESPONSE)

@csrf_exempt
def alert(request):

    data = request.body.decode('utf-8')
    json_data = json.loads(data)
    src_ip = json_data.get('src_ip')
    src_port = json_data.get('src_port')
    dest_ip = json_data.get('dest_ip')
    dest_port = json_data.get('dest_port')
    uid = json_data.get('alert_uid')
    secret = json_data.get('secret')
    host = Enrollment(tenant_id=None, node_system_id=None)
    enrolled_nodes = host.get_enrolled_nodes()

    if not secret == LOGSTASH_SECRET or \
            (not src_ip in enrolled_nodes and not dest_ip in enrolled_nodes):
        return None

    alerts.objects.all().delete()

    alert = alerts(src_ip=src_ip, src_port=src_port, dest_ip=dest_ip, dest_port=dest_port, uid=uid)
    alert.save()

    print(alerts.objects.all())

    return JsonResponse(EMPTY_RESPONSE)

arthur/enroll/views/kafka_views.py
from kafka import KafkaProducer
from kafka import KafkaConsumer
from json import loads
import json
import pickle


def kfk(logs):
    producer = KafkaProducer(bootstrap_servers='192.168.79.134:9092',value_serializer=lambda v: json.dumps(v).encode('utf-8'))
    for log in logs:
        producer.send('test', log)
    print("Successful")


#kfk()

arthur/enroll/templates/enroll/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>{% block title %}Example{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}

</head>

<body>

{% block navbar %}
    {% include  '_items/navbar.html' %}
{% endblock %}

<div class="col-xs-12">
    {% for message in messages %}
        <div class="alert alert-dismissible alert-{{ message.tags }}">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ message }}
        </div>
    {% endfor %}
</div>

<!-- Main jumbotron for a primary marketing message or call to action -->

<div class="container">
    {% block content %}
    {% endblock %}

    <hr>

    <footer>
        <p>&copy; Company 2017</p>
    </footer>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery.min.js'%}"><\/script>')</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

arthur/enroll/templates/enroll/enroll.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body style="padding: 20px;">
  {% crispy form form.helper %}
</body>
</html>

arthur/enroll/templates/enroll/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a
                jumbotron and three supporting pieces of content. Use it as a starting point to create something more
                unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <!-- Example row of columns -->
    <div class="row">
    <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris
            condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod.
            Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta
            felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
            massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
    </div>
    Click <a href="{% url 'edr:enroll' %}">here</a> to access the enrollment page.
{% endblock %}

arthur/enroll/templates/enroll/login.html
{% extends 'enroll/base.html' %}
{% load staticfiles %}
{% block navbar %}{% endblock %}
{% block css %}
    <link href="{% static 'css/users.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <form class="form-signin" action="{% url 'edr:login' %}" method="POST">
        {% csrf_token %}

        <input type="hidden" id="id_next" name="next" value="{{ request.GET.next }}">

        <h2 class="form-signin-heading">Login</h2>

        <label for="id_username" class="sr-only">Username</label>
        <input type="text" placeholder="Username" name="username" id="id_username" class="form-control" required
               autofocus>

        <label for="id_password" class="sr-only">Password</label>
        <input type="password" placeholder="Password" name="password" id="id_password" class="form-control">

        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </form>
{% endblock %}

arthur/enroll/templates/enroll/members_only.html
{% extends 'base.html' %}

{% block content %}
    <div>
        Only logged in users can view this page.
    </div>
{% endblock %}

arthur/enroll/templates/enroll/queries.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body style="padding: 20px;">
  {% crispy form form.helper %}
</body>
</html>

arthur/enroll/templates/enroll/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block css %}
    <link href="{% static 'css/users.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <form class="form-signin" action="{% url 'register' %}" method="POST">
        {% csrf_token %}

        <h2 class="form-signin-heading">Create a new account</h2>

        <label for="id_username" class="sr-only">Email address</label>
        {% render_field form.username class="form-control" placeholder="Username" required="" autofocus="" %}
        {% for error in form.username.errors %}
            <span class="help-block">{{ error }}</span>
        {% endfor %}

        <label for="id_password1" class="sr-only">Password</label>
        {% render_field form.password1 class="form-control" placeholder="Password" required="" type="password" %}
        {% for error in form.password1.errors %}
            <span class="help-block">{{ error }}</span>
        {% endfor %}

        <label for="id_password2" class="sr-only">Password Confirmation</label>
        {% render_field form.password2 class="form-control" placeholder="Password Confirmation" required="" type="password" %}
        {% for error in form.password2.errors %}
            <span class="help-block">{{ error }}</span>
        {% endfor %}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
    </form>
{% endblock %}