arthur/arthur/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('enroll/', include('enroll.urls')),
    path('admin/', admin.site.urls),
]

arthur/enroll/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views

from .views.stats_views import TenantMemberListView, TenantListView

from . import views

app_name = 'edr'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('enroll', views.enroll, name='enroll'),
    path('config', views.config, name='config'),
    path('logger', views.logger, name='logger'),
    path('distributed_read', views.distributed_read, name='distributed_read'),
    path('distributed_write', views.distributed_write, name='distributed_write'),
    path('distributed_query', views.distributed_query, name='distributed_query'),
    path('distributed_results', views.distributed_results, name='distributed_results'),
    path('alert', views.alert, name='alert'),
    path('tenantList', TenantListView.as_view(), name='tenantList'),
    path('members', TenantMemberListView.as_view(), name='members'),
    path('addTenant', views.addTenant, name='addTenant'),
    path('addTenantMember', views.addTenantMember, name='addTenantMember'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('registerUser', views.RegisterView.as_view(), name='register'),
    path('hello', views.HelloView.as_view(), name='hello'),
    path('home', views.HelloView.as_view(), name='home'),
    path('token', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('api/register', views.RegisterNodeView.as_view(), name='api_register'),
    path('api/node_list', views.NodeList.as_view(), name='api_node_list'),
]

arthur/templates/_items/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'edr:members' %}">Members View</a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'edr:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav mr-right">
                <li class="nav-item">
                    <a class="nav-link"">Logged in as {{ user.username }}</a>
                </li>
                <form class="form-inline my-2 my-lg-0" action="{% url 'logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
                </form>
            </ul>
        {% else %}
            <form class="form-inline my-2 my-lg-0" action="{% url 'edr:login' %}" method="POST">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="text" placeholder="Username" aria-label="Username"
                       name="username" id="id_username">
                <input class="form-control mr-sm-2" type="password" placeholder="Password" aria-label="Password"
                       name="password" id="id_password">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign in</button>
            </form>
        {% endif %}
    </div>
</nav>